# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacktodate < Formula
  desc "CLI tool for Stack To Date - track your tech stack lifecycle"
  homepage "https://stacktodate.club"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.1.5/stacktodate_darwin_amd64.tar.gz"
      sha256 "abdf99c91e155b640396c15eeb9d6f7281ddf44ee7656a1fb4d1247fcea33181"

      def install
        bin.install "stacktodate"
      end
    end
    on_arm do
      url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.1.5/stacktodate_darwin_arm64.tar.gz"
      sha256 "550e87aac21ff691a79c216ce7e1cf7e63557a5bd1bd077a251d98e817d1bb19"

      def install
        bin.install "stacktodate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.1.5/stacktodate_linux_amd64.tar.gz"
        sha256 "d6b4d8d01d25a9ff181d9269b2b982ab55a235a408db3ca69db0523272c48bac"

        def install
          bin.install "stacktodate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.1.5/stacktodate_linux_arm64.tar.gz"
        sha256 "08bda6ef6ff3e83204c1ac1b42d7236bc5ec4e0e0bf60169543df9d362546bd4"

        def install
          bin.install "stacktodate"
        end
      end
    end
  end

  test do
    system "#{bin}/stacktodate --version"
  end
end
