# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacktodate < Formula
  desc "CLI tool for Stack To Date - track your tech stack lifecycle"
  homepage "https://stacktodate.club"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.3/stacktodate_darwin_amd64.tar.gz"
      sha256 "0d3203386ee51f4971edd9e888021e6ca137adfa119e055f4a72c0fbf7d487bc"

      def install
        bin.install "stacktodate"
      end
    end
    on_arm do
      url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.3/stacktodate_darwin_arm64.tar.gz"
      sha256 "828d38c35f52a772570c4bc8479d67fafd8f9e40b518123855b46084b8489e2a"

      def install
        bin.install "stacktodate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.3/stacktodate_linux_amd64.tar.gz"
        sha256 "f79842c5c23e188a5bc89129c30215f1fac44624365e1c76d4fd973a5bf56ebd"

        def install
          bin.install "stacktodate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.3/stacktodate_linux_arm64.tar.gz"
        sha256 "87e87adb200928b0a378215f91ba4e2750e038e0e287a2bc8f0e4569735d247c"

        def install
          bin.install "stacktodate"
        end
      end
    end
  end

  test do
    system "#{bin}/stacktodate --version"
  end
end
