# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacktodate < Formula
  desc "CLI tool for Stack To Date - track your tech stack lifecycle"
  homepage "https://stacktodate.club"
  version "0.2.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.2/stacktodate_darwin_amd64.tar.gz"
      sha256 "841256819a0c80ab2fe9f200658d559ac34268a4efe37973837bc216f8a1485c"

      def install
        bin.install "stacktodate"
      end
    end
    on_arm do
      url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.2/stacktodate_darwin_arm64.tar.gz"
      sha256 "5f9850b883e643937cff6a112a4670b2c0ec5a6e1bf9b713895e4037327ba825"

      def install
        bin.install "stacktodate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.2/stacktodate_linux_amd64.tar.gz"
        sha256 "754e6a7fe9db0aa9b643b71b63fb299f10905204145ff4df82ab8351522e71cc"

        def install
          bin.install "stacktodate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.2/stacktodate_linux_arm64.tar.gz"
        sha256 "bb525facabcacbb7dcd63d221212977b9c87162507950b4da30ec88caf4de829"

        def install
          bin.install "stacktodate"
        end
      end
    end
  end

  test do
    system "#{bin}/stacktodate --version"
  end
end
