# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacktodate < Formula
  desc "CLI tool for Stack To Date - track your tech stack lifecycle"
  homepage "https://stacktodate.club"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.0/stacktodate_darwin_amd64.tar.gz"
      sha256 "82a4c0f84a9efb6f2bff2b902705cac210152d5f9819304f69d8d49da71a4b9b"

      def install
        bin.install "stacktodate"
      end
    end
    on_arm do
      url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.0/stacktodate_darwin_arm64.tar.gz"
      sha256 "1ec685068f80f7f355a6da3f8d288ad16ea0f34c67c44748d4ea354c22789cc0"

      def install
        bin.install "stacktodate"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.0/stacktodate_linux_amd64.tar.gz"
        sha256 "b25c5cb7dd860118a19cb8f29c6917c2acddc26150d771b60d689ffc9e67ced6"

        def install
          bin.install "stacktodate"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stacktodate/stacktodate-cli/releases/download/v0.2.0/stacktodate_linux_arm64.tar.gz"
        sha256 "61dd2bb553af8f6cba637e9ecc50e7067a7ac137ffa5d9bfb4162762496b06c9"

        def install
          bin.install "stacktodate"
        end
      end
    end
  end

  test do
    system "#{bin}/stacktodate --version"
  end
end
